export interface DummyContactDataProp {
    fullname: string,
    mictslos_id: string,
    emailaddress1: string,
    address1_telephone1: string,
    address1_city: string,
    address1_country: string,
    address1_line1: string,
    address1_line2: string,
    annualincome_base: string,
    jobtitle: string,
    mictslos_branch: {title: string},
    mictslos_bank: {title: string},
    gendercode: {text: string},
    mictslos_category: {key: number, text: string}[],
    mictslos_contacttype: {key: number, text: string}[],
    birthdate: string,
    mictslos_employersname: string,
    mictslos_bizoperation: {text: string},
    mictslos_bizplaceofincorporation: string,
    mictslos_bizregistrationnumber: string,
    mictslos_bizyears: string,
    mictslos_joindate: string,
    preferredcontactmethodcode: {text: string}
}

export const DummyContactData: DummyContactDataProp[] = [
    {
        "fullname": "Japhet Passah",
        "mictslos_id": "jap001",
        "emailaddress1": "japh@gmail.com",
        "address1_telephone1": "0234567123",
        "address1_city": "Madina",
        "address1_country": "Ghana",
        "address1_line1": "",
        "address1_line2": "",
        "annualincome_base": "30000",
        "jobtitle": "Software developer",
        "mictslos_branch": {"title": "Achimota"},
        "mictslos_bank": {"title": "UBA"},
        "gendercode": {"text": "Male"},
        "mictslos_category":[{ "key": 1, "text": "Customer"}, { "key": 2, "text": "Non-Customer"}],
        "mictslos_contacttype": [{ "key": 1, "text": "Individual"}, { "key": 2, "text": "Company"}],
        "birthdate": "5 Feb 2000",
        "mictslos_employersname": "MICTS",
        "mictslos_bizoperation": {"text": ""},
        "mictslos_bizplaceofincorporation": "empty",
        "mictslos_bizregistrationnumber": "empty",
        "mictslos_bizyears": "2024",
        "mictslos_joindate": "23 July 2021",
        "preferredcontactmethodcode": {"text": "Any"}
    },
    {
        "fullname": "Japhet Passah",
        "mictslos_id": "jap001",
        "emailaddress1": "japh@gmail.com",
        "address1_telephone1": "0234567123",
        "address1_city": "Madina",
        "address1_country": "Ghana",
        "address1_line1": "",
        "address1_line2": "",
        "annualincome_base": "30000",
        "jobtitle": "Software developer",
        "mictslos_branch": {"title": "Achimota"},
        "mictslos_bank": {"title": "UBA"},
        "gendercode": {"text": "Male"},
        "mictslos_category":[{ "key": 1, "text": "Customer"}, { "key": 2, "text": "Non-Customer"}],
        "mictslos_contacttype": [{ "key": 1, "text": "Individual"}, { "key": 2, "text": "Company"}],
        "birthdate": "5 Feb 2000",
        "mictslos_employersname": "MICTS",
        "mictslos_bizoperation": {"text": ""},
        "mictslos_bizplaceofincorporation": "empty",
        "mictslos_bizregistrationnumber": "empty",
        "mictslos_bizyears": "2024",
        "mictslos_joindate": "23 July 2021",
        "preferredcontactmethodcode": {"text": "Any"}
    }
]